# Preface {-}

This is the third edition of *Statistical Modeling: A Fresh Approach*. The use of the phrase "fresh approach" in the title is a promise that there is genuinely fresh in the addition. 

In the first edition (2009), the *Fresh Approach* included

* the use of linear modeling with multiple explanatory variabes as the introduction to statistics
* integration of technical computing as an essential conceptual tool
* using geometry as a way to make the profound concepts of  linear modeling accessible. (The traditional use of linear algebra rules out any student without a strong mathematics background, and even then obscures as much as it illuminates.)
* taking causality seriously even in observational data.

The second edition (2011) was a sort of freshening up. The primary change was the integration of the fledgling `mosaic` package for R. Much of `mosaic` emerged from the first edition, but it was dramatically extended and improved by collaboration with Randall Pruim of Calvin College and Nicholas Horton of Amherst College with support from the National Science Foundation (NSF DUE-0920350).

Many of the ideas in the first and second editions of *Fresh Approach* are now moving into the mainstream of statistical pedagogy. It's especially gratifying that the central statement of goals for introductory statistics --- the American Statistical Association's GAISE report --- has added two new emphases: multivariable thinking and using computing to explore statistical concepts. The `mosaic` package has been downloaded hundreds of thousands of times.

The pace of technical change since 2011 has been remarkable.

* Advances in computing
    - The R community has expanded tremendously.
    - The infrastructure behind R has become much more powerful and sophisticated. Much of this has been due to the open-source software provided by RStudio.
    - R itself has become dramatically more speedy and is able to take on industrial-sized problems.
    - R has been integrated into publishing. Systems such as R/markdown, Shiny, Bookdown, DataCamp, git, and so on draw on internet technologies such as HTML5 and Javascript to make it practical to bring computing into books in an interactive way. They also support broad collaboration among authors and other contributors.
    - Domain specific systems in R such as `dplyr` and `ggplot2` have joined `mosaic` in providing the power of programming without the syntactical complexity of all-purpose languages.

* Changes in statistics
    - much increased interest in machine-learning technologies.
    - the emergence of data science
    - the wide availability of massive datasets

These innovations in computing and statistical emphasis call for a new pedagogy. On a conceptual level, machine-learning ideas such as cross-validation provide the means to sidestep much of the mathematical intricacies involved in interpreting linear models as well as the ability to move beyond the linear model into other model architectures which can be better suited to the process. For instance, recursive partitioning models make it relatively easy to interpret complex interactions among explanatory variable and provide a ready means to explore complex datasets.


